"""cria schema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-07-11 07:30:40.690101
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Sequences que geram os códigos legíveis (CAR000001, DRV000001...).
# PRECISAM existir antes das tabelas: o DEFAULT da coluna `code` chama nextval().
CODE_SEQUENCES = [
    "user_code_seq",
    "vehicle_code_seq",
    "driver_code_seq",
    "contract_code_seq",
    "revenue_code_seq",
    "expense_code_seq",
    "maintenance_code_seq",
    "fine_code_seq",
    "inspection_code_seq",
]


def upgrade() -> None:
    for seq in CODE_SEQUENCES:
        op.execute(f"CREATE SEQUENCE IF NOT EXISTS {seq}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=120), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'login_failed', name='audit_action', native_enum=False, length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_code', sa.String(length=12), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_entidade', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_quando', 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('group_name', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_items')),
    sa.UniqueConstraint('key', name=op.f('uq_checklist_items_key'))
    )
    op.create_table('drivers',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'DRV' || lpad(nextval('driver_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('cnh_number', sa.String(length=20), nullable=True),
    sa.Column('cnh_category', sa.String(length=5), nullable=True),
    sa.Column('cnh_expiry', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact', sa.String(length=120), nullable=True),
    sa.Column('address_street', sa.String(length=160), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_city', sa.String(length=80), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=9), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='driver_status', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers'))
    )
    op.create_index(op.f('ix_drivers_code'), 'drivers', ['code'], unique=True)
    op.create_index(op.f('ix_drivers_cpf'), 'drivers', ['cpf'], unique=True)
    op.create_index(op.f('ix_drivers_full_name'), 'drivers', ['full_name'], unique=False)
    op.create_index(op.f('ix_drivers_phone'), 'drivers', ['phone'], unique=False)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_capex', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_expense_categories_code'))
    )
    op.create_table('users',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'USR' || lpad(nextval('user_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operador', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_code'), 'users', ['code'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'CAR' || lpad(nextval('vehicle_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('plate', sa.String(length=8), nullable=False),
    sa.Column('renavam', sa.String(length=20), nullable=True),
    sa.Column('chassi', sa.String(length=30), nullable=True),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('fuel_type', sa.Enum('flex', 'gasolina', 'etanol', 'diesel', 'gnv', 'hibrido', 'eletrico', name='fuel_type', native_enum=False, length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_odometer', sa.Integer(), nullable=False),
    sa.Column('current_odometer', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_market_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('available', 'rented', 'maintenance', 'sold', 'inactive', name='vehicle_status', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(sale_price IS NULL) = (sale_date IS NULL)', name=op.f('ck_vehicles_venda_preco_e_data_juntos')),
    sa.CheckConstraint('current_odometer >= 0', name=op.f('ck_vehicles_odometro_nao_negativo')),
    sa.CheckConstraint('purchase_price >= 0', name=op.f('ck_vehicles_purchase_price_nao_negativo')),
    sa.CheckConstraint('sale_price IS NULL OR sale_price >= 0', name=op.f('ck_vehicles_sale_price_nao_negativo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('chassi', name=op.f('uq_vehicles_chassi')),
    sa.UniqueConstraint('renavam', name=op.f('uq_vehicles_renavam'))
    )
    op.create_index(op.f('ix_vehicles_code'), 'vehicles', ['code'], unique=True)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('contracts',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'CTR' || lpad(nextval('contract_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('weekly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_weekday', sa.Integer(), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_status', sa.Enum('held', 'settled', name='deposit_status', native_enum=False, length=20), nullable=False),
    sa.Column('deposit_returned_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'finished', 'canceled', name='contract_status', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('billing_weekday BETWEEN 0 AND 6', name=op.f('ck_contracts_dia_cobranca_valido')),
    sa.CheckConstraint('deposit_amount >= 0', name=op.f('ck_contracts_caucao_nao_negativa')),
    sa.CheckConstraint('deposit_returned_amount >= 0 AND deposit_returned_amount <= deposit_amount', name=op.f('ck_contracts_caucao_devolvida_dentro_do_limite')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_contracts_fim_depois_do_inicio')),
    sa.CheckConstraint('weekly_amount > 0', name=op.f('ck_contracts_valor_semanal_positivo')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_contracts_driver_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_contracts_vehicle_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_index(op.f('ix_contracts_code'), 'contracts', ['code'], unique=True)
    op.create_index(op.f('ix_contracts_driver_id'), 'contracts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_vehicle_id'), 'contracts', ['vehicle_id'], unique=False)
    op.create_index('uq_contracts_veiculo_ativo', 'contracts', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('documents',
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('contrato_pdf', 'confissao_divida', 'assinatura', 'nota_fiscal', 'cnh', 'crlv', 'notificacao', 'foto', 'outro', name='document_kind', native_enum=False, length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    op.create_index('ix_documents_entidade', 'documents', ['entity_type', 'entity_id'], unique=False)
    op.create_table('fines',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'MUL' || lpad(nextval('fine_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('infraction_date', sa.Date(), nullable=False),
    sa.Column('ait_number', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('driver_indication_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'canceled', name='fine_status', native_enum=False, length=20), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'paid') = (paid_on IS NOT NULL)", name=op.f('ck_fines_paga_exige_data')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_fines_valor_positivo')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_fines_driver_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_fines_vehicle_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fines'))
    )
    op.create_index(op.f('ix_fines_code'), 'fines', ['code'], unique=True)
    op.create_index(op.f('ix_fines_driver_id'), 'fines', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fines_infraction_date'), 'fines', ['infraction_date'], unique=False)
    op.create_index(op.f('ix_fines_status'), 'fines', ['status'], unique=False)
    op.create_index(op.f('ix_fines_vehicle_id'), 'fines', ['vehicle_id'], unique=False)
    op.create_index('ix_fines_veiculo_data', 'fines', ['vehicle_id', 'infraction_date'], unique=False)
    op.create_table('maintenances',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'MAN' || lpad(nextval('maintenance_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_maintenances_valor_nao_negativo')),
    sa.CheckConstraint('odometer >= 0', name=op.f('ck_maintenances_odometro_nao_negativo')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_maintenances_vehicle_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenances'))
    )
    op.create_index(op.f('ix_maintenances_code'), 'maintenances', ['code'], unique=True)
    op.create_index(op.f('ix_maintenances_performed_on'), 'maintenances', ['performed_on'], unique=False)
    op.create_index(op.f('ix_maintenances_vehicle_id'), 'maintenances', ['vehicle_id'], unique=False)
    op.create_index('ix_maintenances_veiculo_data', 'maintenances', ['vehicle_id', 'performed_on'], unique=False)
    op.create_table('expenses',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'DES' || lpad(nextval('expense_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.UUID(), nullable=True),
    sa.Column('fine_id', sa.UUID(), nullable=True),
    sa.Column('supplier_name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('competence_date', sa.Date(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', name='expense_status', native_enum=False, length=20), nullable=False),
    sa.Column('origin', sa.Enum('manual', 'maintenance', 'fine', name='expense_origin', native_enum=False, length=20), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=True),
    sa.Column('document_number', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'paid') = (paid_on IS NOT NULL)", name=op.f('ck_expenses_paga_exige_data_pagamento')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_valor_positivo')),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_expenses_driver_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], name=op.f('fk_expenses_fine_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenances.id'], name=op.f('fk_expenses_maintenance_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_expenses_vehicle_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_code'), 'expenses', ['code'], unique=True)
    op.create_index(op.f('ix_expenses_competence_date'), 'expenses', ['competence_date'], unique=False)
    op.create_index(op.f('ix_expenses_driver_id'), 'expenses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_expenses_fine_id'), 'expenses', ['fine_id'], unique=False)
    op.create_index(op.f('ix_expenses_maintenance_id'), 'expenses', ['maintenance_id'], unique=False)
    op.create_index(op.f('ix_expenses_paid_on'), 'expenses', ['paid_on'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_vehicle_id'), 'expenses', ['vehicle_id'], unique=False)
    op.create_index('ix_expenses_veiculo_pagamento', 'expenses', ['vehicle_id', 'paid_on'], unique=False)
    op.create_table('inspections',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'VST' || lpad(nextval('inspection_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('entrega', 'devolucao', 'periodica', name='inspection_kind', native_enum=False, length=20), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('fuel_level', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fuel_level BETWEEN 0 AND 100', name=op.f('ck_inspections_combustivel_entre_0_e_100')),
    sa.CheckConstraint('odometer >= 0', name=op.f('ck_inspections_odometro_nao_negativo')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_inspections_contract_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_inspections_driver_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inspections_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_inspections_vehicle_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    op.create_index(op.f('ix_inspections_code'), 'inspections', ['code'], unique=True)
    op.create_index(op.f('ix_inspections_contract_id'), 'inspections', ['contract_id'], unique=False)
    op.create_index(op.f('ix_inspections_driver_id'), 'inspections', ['driver_id'], unique=False)
    op.create_index(op.f('ix_inspections_inspected_at'), 'inspections', ['inspected_at'], unique=False)
    op.create_index(op.f('ix_inspections_kind'), 'inspections', ['kind'], unique=False)
    op.create_index(op.f('ix_inspections_vehicle_id'), 'inspections', ['vehicle_id'], unique=False)
    op.create_table('revenues',
    sa.Column('code', sa.String(length=12), server_default=sa.text("'REC' || lpad(nextval('revenue_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('fine_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('aluguel', 'reembolso', 'caucao_retida', 'outros', name='revenue_category', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('competence_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'partial', 'paid', 'canceled', name='revenue_status', native_enum=False, length=20), nullable=False),
    sa.Column('origin', sa.Enum('manual', 'contract', name='revenue_origin', native_enum=False, length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_revenues_valor_positivo')),
    sa.CheckConstraint('paid_amount >= 0 AND paid_amount <= amount', name=op.f('ck_revenues_pago_dentro_do_valor')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_revenues_contract_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_revenues_driver_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fine_id'], ['fines.id'], name=op.f('fk_revenues_fine_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_revenues_vehicle_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenues')),
    sa.UniqueConstraint('contract_id', 'period_start', name='uq_revenues_contrato_semana')
    )
    op.create_index(op.f('ix_revenues_category'), 'revenues', ['category'], unique=False)
    op.create_index(op.f('ix_revenues_code'), 'revenues', ['code'], unique=True)
    op.create_index(op.f('ix_revenues_competence_date'), 'revenues', ['competence_date'], unique=False)
    op.create_index(op.f('ix_revenues_contract_id'), 'revenues', ['contract_id'], unique=False)
    op.create_index(op.f('ix_revenues_driver_id'), 'revenues', ['driver_id'], unique=False)
    op.create_index(op.f('ix_revenues_due_date'), 'revenues', ['due_date'], unique=False)
    op.create_index('ix_revenues_em_aberto', 'revenues', ['due_date'], unique=False, postgresql_where=sa.text("status IN ('pending', 'partial')"))
    op.create_index(op.f('ix_revenues_fine_id'), 'revenues', ['fine_id'], unique=False)
    op.create_index(op.f('ix_revenues_status'), 'revenues', ['status'], unique=False)
    op.create_index(op.f('ix_revenues_vehicle_id'), 'revenues', ['vehicle_id'], unique=False)
    op.create_index('ix_revenues_veiculo_vencimento', 'revenues', ['vehicle_id', 'due_date'], unique=False)
    op.create_table('inspection_items',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('ok', 'avaria', 'faltando', 'na', name='item_condition', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], name=op.f('fk_inspection_items_checklist_item_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_inspection_items_inspection_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_items')),
    sa.UniqueConstraint('inspection_id', 'checklist_item_id', name='uq_inspection_items_item')
    )
    op.create_index(op.f('ix_inspection_items_inspection_id'), 'inspection_items', ['inspection_id'], unique=False)
    op.create_table('inspection_photos',
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('frente', 'traseira', 'lateral_esquerda', 'lateral_direita', 'interior', 'painel', 'motor', 'pneus', 'avaria', 'assinatura', 'outros', name='photo_category', native_enum=False, length=20), nullable=False),
    sa.Column('caption', sa.String(length=160), nullable=True),
    sa.Column('original_filename', sa.String(length=200), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_inspection_photos_inspection_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_photos')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_inspection_photos_storage_key'))
    )
    op.create_index(op.f('ix_inspection_photos_category'), 'inspection_photos', ['category'], unique=False)
    op.create_index(op.f('ix_inspection_photos_inspection_id'), 'inspection_photos', ['inspection_id'], unique=False)
    op.create_table('revenue_payments',
    sa.Column('revenue_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('pix', 'dinheiro', 'transferencia', 'cartao', 'boleto', 'outro', name='payment_method', native_enum=False, length=20), nullable=False),
    sa.Column('receipt_ref', sa.String(length=80), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_revenue_payments_valor_positivo')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_revenue_payments_created_by_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revenue_id'], ['revenues.id'], name=op.f('fk_revenue_payments_revenue_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_payments'))
    )
    op.create_index(op.f('ix_revenue_payments_paid_on'), 'revenue_payments', ['paid_on'], unique=False)
    op.create_index(op.f('ix_revenue_payments_revenue_id'), 'revenue_payments', ['revenue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_payments_revenue_id'), table_name='revenue_payments')
    op.drop_index(op.f('ix_revenue_payments_paid_on'), table_name='revenue_payments')
    op.drop_table('revenue_payments')
    op.drop_index(op.f('ix_inspection_photos_inspection_id'), table_name='inspection_photos')
    op.drop_index(op.f('ix_inspection_photos_category'), table_name='inspection_photos')
    op.drop_table('inspection_photos')
    op.drop_index(op.f('ix_inspection_items_inspection_id'), table_name='inspection_items')
    op.drop_table('inspection_items')
    op.drop_index('ix_revenues_veiculo_vencimento', table_name='revenues')
    op.drop_index(op.f('ix_revenues_vehicle_id'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_status'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_fine_id'), table_name='revenues')
    op.drop_index('ix_revenues_em_aberto', table_name='revenues', postgresql_where=sa.text("status IN ('pending', 'partial')"))
    op.drop_index(op.f('ix_revenues_due_date'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_driver_id'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_contract_id'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_competence_date'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_code'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_category'), table_name='revenues')
    op.drop_table('revenues')
    op.drop_index(op.f('ix_inspections_vehicle_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_kind'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspected_at'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_driver_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_contract_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_code'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index('ix_expenses_veiculo_pagamento', table_name='expenses')
    op.drop_index(op.f('ix_expenses_vehicle_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_paid_on'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_maintenance_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_fine_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_driver_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_competence_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_code'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_maintenances_veiculo_data', table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_vehicle_id'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_performed_on'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_code'), table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_index('ix_fines_veiculo_data', table_name='fines')
    op.drop_index(op.f('ix_fines_vehicle_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_status'), table_name='fines')
    op.drop_index(op.f('ix_fines_infraction_date'), table_name='fines')
    op.drop_index(op.f('ix_fines_driver_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_code'), table_name='fines')
    op.drop_table('fines')
    op.drop_index('ix_documents_entidade', table_name='documents')
    op.drop_table('documents')
    op.drop_index('uq_contracts_veiculo_ativo', table_name='contracts', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_contracts_vehicle_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_driver_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_code'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_code'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_code'), table_name='users')
    op.drop_table('users')
    op.drop_table('expense_categories')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_phone'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_full_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_cpf'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_code'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_table('checklist_items')
    op.drop_index('ix_audit_logs_quando', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entidade', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

    for seq in CODE_SEQUENCES:
        op.execute(f"DROP SEQUENCE IF EXISTS {seq}")
