"""lixeira em receitas e despesas; despesa da empresa sem veiculo

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-13 00:01:59.128166
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('expenses', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_expenses_deleted_at'), 'expenses', ['deleted_at'], unique=False)
    op.add_column('revenues', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_revenues_deleted_at'), 'revenues', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenues_deleted_at'), table_name='revenues')
    op.drop_column('revenues', 'deleted_at')
    op.drop_index(op.f('ix_expenses_deleted_at'), table_name='expenses')
    op.alter_column('expenses', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('expenses', 'deleted_at')
    # ### end Alembic commands ###
